---

- name: PHP-FPM | packages
  tags:
    - package
  package:
    name: 
      - php-fpm
      - php-sqlite3

- name: PHP-FPM | config
  tags:
  - config
  template:
    src: "{{ item.src }}.j2"
    dest: "{{ item.dest }}/{{ item.src }}"
  with_items:
  - { src: php-fpm, dest: /etc/nginx/ }
  - { src: php-handler.conf, dest: /etc/nginx/conf.d/ }
  - { src: php.ini, dest: "/etc/php/{{ php_ver }}/fpm/" }
  - { src: php-fpm.conf, dest: "/etc/php/{{ php_ver }}/fpm/" }
  - { src: www.conf, dest: "/etc/php/{{ php_ver }}/fpm/pool.d/" }
  notify: restart php-fpm

- name: PHP-FPM | logrotate
  tags:
    - logrotate
  copy:
    dest: "/etc/logrotate.d/php{{ php_ver }}-fpm"
    content: "/var/log/php{{ php_ver }}-fpm.log {}"

- name: PHP-FPM | service
  tags:
  - service
  service:
    name: "php{{ php_ver }}-fpm"
    state: started
    enabled: yes
